---
- name: user module demo
  hosts: all
  become: true
  vars:
    myuser: "example"
  tasks:
    - name: password min expiration
      ansible.builtin.user:
        name: "{{ myuser }}"
        password_expire_min: 7

    - name: password max expiration
      ansible.builtin.user:
        name: "{{ myuser }}"
        password_expire_max: 90
