---
- name: fetch module demo
  hosts: all
  become: false
  vars:
    myfile: 'C:\Users\vagrant\Desktop\example.txt'
    dump_dir: "logs"
  tasks:
    - name: fetch file
      ansible.builtin.fetch:
        src: "{{ myfile }}"
        dest: "{{ dump_dir }}"
